# Servidor
server.port=8080

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/financiero_db
spring.datasource.username=postgres
spring.datasource.password=Admin1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS
spring.web.cors.allowed-origins=http://localhost:5173

# Logs
logging.level.com.isw.financiero=INFO
